### ISSUE TITLE
Great idea!

### ISSUE THREAD

**Issue by FGRibreau** [djanowski/yoredis#1]
Indeed, it may be sometime a good idea to build from the ground up promise support instead of wrapping a lib at a higher level :)

Even if it's still a WiP, yoredis will be shared in our next [RedisWeekly](http://redisweekly.com/)! Once published (in a matter of minutes) you will be able to see your [project description here](http://redisweekly.com/archive/140.html) :)

**Comment by djanowski** [comment]
Thank you @FGRibreau!
